spring:
  http:
    encoding:
        charset: UTF-8
        enabled: true
        force: true
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
  jackson:
    serialization:
      write_dates_as_timestamps: false

server:
  port: 8080
  context-path: /rest

